# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
    
- task: BatchScript@1
  inputs:
    filename: ingresador.bat
    arguments: ant 4.1.8.5
    workingFolder: $(Agent.WorkFolder)\Test\app
